db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles
web:
  image: pierreozoux/tosdr2
  environment:
    - MONGO_URL=mongodb://db:27017/meteor
    - ROOT_URL
    - MAIL_URL
  links:
    - db:db
  volumes:
    - ./logs:/home/app/logs
